# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2717eb5700652802ac98ee01746370d0af202982f4aa87a2cac326aedcefaba8f016b620601fa90e55bad41b1df4fd885cdba7a9aed3e8507c88c7e9b0c22b42

test:
  secret_key_base: e1f510008d9cdcbed25a41b7dc18d34dbe17e812ba54fbb6b9184224b8e6404421e7f5d6e9e5a3647b4416dfdaf1808d3d8bb06aacb4709908a84c5f86cdfa5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
